import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Halo Protocol",
  description:
    "Terms of Service for Halo Protocol. Read our terms and conditions for using the decentralized lending circle platform.",
  openGraph: {
    title: "Terms of Service - Halo Protocol",
    description:
      "Terms of Service for Halo Protocol. Read our terms and conditions for using the decentralized lending circle platform.",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0B0F1A]">
      <div className="mx-auto max-w-6xl px-4 py-20">
        {/* Header */}
        <div className="mb-16 text-center">
          <h1 className="mb-4 text-4xl font-bold text-white sm:text-5xl">
            Terms of Service
          </h1>
          <p className="text-neutral-400">Last updated: February 2026</p>
        </div>

        {/* Content */}
        <div className="glass-card rounded-2xl border border-white/10 p-8 sm:p-10">
          <div className="space-y-10">
            {/* Acceptance */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                1. Acceptance of Terms
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                By accessing or using the Halo Protocol platform at gethalo.fun
                (&ldquo;the Platform&rdquo;), you agree to be bound by these
                Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to
                these Terms, do not use the Platform. We reserve the right to
                modify these Terms at any time, and your continued use
                constitutes acceptance of any changes.
              </p>
            </section>

            {/* Description */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                2. Description of Service
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                Halo Protocol is a decentralized lending circle (ROSCA) platform
                built on the Stacks blockchain. The Platform allows users to
                create and participate in lending circles, make contributions,
                receive payouts, and build on-chain credit scores. The Platform
                interacts with smart contracts deployed on the Stacks blockchain.
              </p>
            </section>

            {/* Testnet Disclaimer */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                3. Testnet Disclaimer
              </h2>
              <div className="rounded-lg border border-yellow-500/20 bg-yellow-500/5 p-4">
                <p className="text-neutral-400 leading-relaxed">
                  <strong className="text-yellow-400">Important:</strong> Halo
                  Protocol is currently deployed on the Stacks testnet. Testnet
                  tokens (including mock hUSD and mock sBTC) have no real-world
                  value. The testnet environment is used for testing and
                  development purposes. Features, functionality, and smart
                  contracts may change significantly before any mainnet
                  deployment. Do not send real assets to testnet addresses.
                </p>
              </div>
            </section>

            {/* No Financial Advice */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                4. No Financial Advice
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                Nothing on the Platform constitutes financial, investment, legal,
                or tax advice. Halo Protocol does not recommend any specific
                financial actions. Credit scores generated by the protocol are
                on-chain metrics based on circle participation and should not be
                interpreted as traditional credit ratings. You are solely
                responsible for your financial decisions. Consult a qualified
                professional before making financial decisions.
              </p>
            </section>

            {/* Use at Own Risk */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                5. Use at Your Own Risk
              </h2>
              <p className="mb-4 text-neutral-400 leading-relaxed">
                You acknowledge and agree that your use of the Platform is at
                your sole risk. The Platform is provided on an &ldquo;as
                is&rdquo; and &ldquo;as available&rdquo; basis without
                warranties of any kind, either express or implied.
              </p>
              <p className="text-neutral-400 leading-relaxed">
                We do not guarantee that the Platform will be uninterrupted,
                error-free, or free from vulnerabilities. You are responsible for
                maintaining the security of your wallet and private keys.
              </p>
            </section>

            {/* Smart Contract Risks */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                6. Smart Contract Risks
              </h2>
              <p className="mb-4 text-neutral-400 leading-relaxed">
                The Platform relies on smart contracts deployed on the Stacks
                blockchain. While our smart contracts are written in Clarity (a
                decidable language) and have undergone internal security review,
                you acknowledge the following risks:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-neutral-400">
                <li>
                  Smart contracts may contain bugs or vulnerabilities that could
                  result in loss of funds
                </li>
                <li>
                  Blockchain transactions are irreversible once confirmed
                </li>
                <li>
                  Network congestion or issues on the Stacks blockchain may
                  affect transaction processing
                </li>
                <li>
                  Changes to the Stacks blockchain protocol could affect smart
                  contract behavior
                </li>
                <li>
                  Circle participants may default on contributions, and while
                  this is recorded on-chain, recovery of funds is not guaranteed
                </li>
              </ul>
            </section>

            {/* Eligibility */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                7. Eligibility
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                You must be at least 18 years old and legally capable of
                entering into binding agreements to use the Platform. By using
                the Platform, you represent that you meet these requirements. You
                are responsible for ensuring that your use of the Platform
                complies with all applicable laws in your jurisdiction.
              </p>
            </section>

            {/* User Conduct */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                8. User Conduct
              </h2>
              <p className="mb-4 text-neutral-400 leading-relaxed">
                You agree not to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-neutral-400">
                <li>
                  Use the Platform for any unlawful purpose or in violation of
                  any applicable laws
                </li>
                <li>
                  Attempt to exploit, hack, or interfere with the Platform or
                  its smart contracts
                </li>
                <li>
                  Create multiple accounts to circumvent rate limits or abuse
                  the faucet
                </li>
                <li>
                  Impersonate other users or misrepresent your identity
                </li>
                <li>
                  Use automated systems or bots to interact with the Platform
                  without authorization
                </li>
                <li>
                  Deliberately default on circle contributions with the intent
                  to defraud other participants
                </li>
              </ul>
            </section>

            {/* Intellectual Property */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                9. Intellectual Property
              </h2>
              <p className="mb-4 text-neutral-400 leading-relaxed">
                Halo Protocol is open-source software released under the MIT
                License. You are free to use, modify, and distribute the source
                code in accordance with the terms of the MIT License.
              </p>
              <p className="text-neutral-400 leading-relaxed">
                The Halo Protocol name, logo, and brand assets are trademarks of
                the Halo Protocol project. Use of these trademarks requires
                prior written consent except as permitted for reasonable
                attribution purposes.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                10. Limitation of Liability
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                To the maximum extent permitted by law, Halo Protocol, its
                contributors, and its affiliates shall not be liable for any
                indirect, incidental, special, consequential, or punitive
                damages, including but not limited to loss of funds, loss of
                data, loss of profits, or loss of goodwill, arising out of or
                related to your use of or inability to use the Platform, even if
                we have been advised of the possibility of such damages.
              </p>
            </section>

            {/* Indemnification */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                11. Indemnification
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                You agree to indemnify and hold harmless Halo Protocol, its
                contributors, and affiliates from any claims, damages, losses,
                liabilities, and expenses (including legal fees) arising out of
                or related to your use of the Platform, your violation of these
                Terms, or your violation of any rights of a third party.
              </p>
            </section>

            {/* Termination */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                12. Termination
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                We may suspend or terminate your access to the Platform at any
                time, without prior notice, for conduct that we believe violates
                these Terms or is harmful to the Platform or other users. Note
                that on-chain data and smart contract interactions are immutable
                and will persist on the blockchain regardless of account status.
              </p>
            </section>

            {/* Governing Law */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                13. Governing Law
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                These Terms shall be governed by and construed in accordance
                with applicable law. Any disputes arising from these Terms or
                your use of the Platform shall be resolved through good-faith
                negotiation. If negotiation fails, disputes shall be resolved
                through binding arbitration in accordance with applicable
                arbitration rules.
              </p>
            </section>

            {/* Changes */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                14. Changes to Terms
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                We reserve the right to modify these Terms at any time. Changes
                will be effective immediately upon posting to the Platform. We
                will update the &ldquo;Last updated&rdquo; date at the top of
                this page. Your continued use of the Platform after changes are
                posted constitutes acceptance of the revised Terms.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                15. Contact
              </h2>
              <p className="text-neutral-400 leading-relaxed">
                If you have questions about these Terms of Service, please
                contact us at{" "}
                <a
                  href="mailto:founder@usehalo.fun"
                  className="text-violet-400 hover:text-violet-300 underline"
                >
                  founder@usehalo.fun
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
